# Generated by Django 4.1.1 on 2022-10-03 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_itenscompra"),
    ]

    operations = [
        migrations.RemoveField(model_name="itenscompra", name="compra",),
        migrations.DeleteModel(name="Compra",),
        migrations.DeleteModel(name="ItensCompra",),
    ]
